### ISSUE TITLE
친구한테 모든 권한을 주고 오피만 뺐는데 모두 다 안됩니다.

### ISSUE THREAD

**Issue by jini5012** [noonmaru/regions#2]
별님 영상보고 신기해서 하고 싶었는데 몇 달후에 나오더라고요. 그래서 친구하고 해봤더니 안되요. 모든 권한 다주고 오피만 뺐습니다. 왜 안되죠?

**Comment by devil0414** [comment]
플러그인 어떻게 적용해요?
