### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by devil0414** [noonmaru/regions#5]
들어가고 나갈 수 있는 권한을 줬는데도 들어가거나 나갈 수 없습니다.

**Comment by devil0414** [comment]
그리고 플러그인 사용하는 방법도 알려주세요.

**Comment by jini5012** [comment]
빌드하시고 서버 plugins에다가 너으면 되는데요?

**Comment by devil0414** [comment]
이미 해결했습니다. 깜빡하고 이슈를 안 닫고 있었네요.
